### ISSUE TITLE
unicode character issues from minecraft data (since 1.8?)

### ISSUE THREAD

**Issue by ShadeDream** [overviewer/Minecraft-Overviewer#1188]
I'm using a modified version of the script in the documentation for showing signs as POIs on the map:

    def signFilter(poi):
        if poi['id'] == 'Sign':
            return "\n".join([poi['Text1'], poi['Text2'], poi['Text3'], poi['Text4']])

It appears that many characters are being encoded as unicode strings (`\u0027` instead of an apostrophe for example). It sounds like this is going on in various places as I've seen tickets related to this elsewhere due to the minecraft data files now being in UTF8 format rather than ASCII by default now.

**Comment by j3rd** [comment]
Add  .replace('"',"")    and  .decode("unicode-escape")

```python
def signFilter(poi):
    if poi["id"] == "Sign":
        return = "\n".join([poi["Text1"], poi["Text2"], poi["Text3"], poi["Text4"]]).replace('"',"").decode("unicode-escape")
```

**Comment by CounterPillow** [comment]
As stated in #1198, this issue has been resolved with a workaround and the signFilter as written in the docs works again. Anyone finding this issue because they are having troubles with signs should **not** use the filter by j3rd, but instead use the regular signFilter as it appears in the documentation and update their Overviewer to version 0.12.58 or later.
