### ISSUE TITLE
Render Cave: Only lit by player placed blocks

### ISSUE THREAD

**Issue by ottk3** [overviewer/Minecraft-Overviewer#1201]
Is there a way to only render caves lit by player placed blocks like torch, lantern, lava etc.?
I would like to render underground buildings by ignoring undiscovered areas.

**Comment by tswsl1989** [comment]
See issues #585 and #503 (and probably others).

Overviewer doesn't calculate lighting levels itself, it applies the lighting value calculated by Minecraft. This means that we would need to replicate those calculations at render time in order to distinguish between light from torches and lanterns vs light from lava. 

If your buildings are relatively fixed sizes, you could try combining the cave mode with the crop feature to produce renders of each building. That would still show unexplored areas that occur near to those buildings though.

**Comment by ottk3** [comment]
Whoops, sorry for the duplicate --> #503
