### ISSUE TITLE
[Question] JSON format, does whitespace matter?

### ISSUE THREAD

**Issue by LeadMagnet** [overviewer/Minecraft-Overviewer#1259]
I am dynamically creating most of the JSON files in the final rendered maps to create custom tags and markers. I'm doing this from a .Net (4.5.2) windows service using the NewtonSoft JSON libraries on NuGet.

When I perform a "remove" on formatting or indentation whitespace, the website will not load the file. Put the formatting and indentation whitespace back in, it works fine. This happens on all JSON files in the rendered site.

Weirdness! I don't know JSON well enough to visually see what is wrong. Could this be a JSON serialization error in the Google API?

**Comment by CounterPillow** [comment]
Whitespace is completely ignored in the JSON syntax outside of string literals.

Please further elaborate on what you mean by "the website will not load the file", since this can be completely unrelated to the changes you make to the JSON. Perhaps you are not properly writing out the JSON files in one case. The developer console in your browser should tell you what exactly fails.

**Comment by LeadMagnet** [comment]
Debug window is not giving an error at all. Neither is Fiddler. No idea why this happens, not a problem, just weird.

The output JSON (minified) simply will not load in the webpage. If I take the same file and manually put the formatting back in (https://jsonformatter.curiousconcept.com), works fine. Not an issue, turns out Newtonsoft libraries have custom settings for formatting so have got a version of the JSON output working that is fully automated. Don't think this is an Overviewer issue anyway, just thought I'd ask if someone else had seen this behaviour.

**Comment by CounterPillow** [comment]
I'll close this then since it's not an overviewer issue
