### ISSUE TITLE
Avatar Lookup Returns Server Error

### ISSUE THREAD

**Issue by iantpryor** [overviewer/Minecraft-Overviewer#1294]
If a player has the default skin, the lookup for avatar is returning a server error. (Server Error
Something broke while finding this page.)

If a player has a custom skin, it's working as expected.

**Comment by agrif** [comment]
We changed the avatar script yesterday to start pulling skins from Mojang directly (instead of the old Amazon system) and probably broke something we didn't notice. Do you have a player name that you know uses a default skin? If you could send me a private github message with it, that would be great.

**Comment by CounterPillow** [comment]
@agrif Uh, GitHub removed messaging a few years ago if I remember correctly.

**Comment by agrif** [comment]
Oh! Yes they did. Email works too, shoot me a line at agrif@overviewer.org

**Comment by iantpryor** [comment]
Seems to be resolved, it's working again.

**Comment by CounterPillow** [comment]
Strange. I'll close this then. Let us know if the error returns.
