### ISSUE TITLE
1.10 bone texture not showing up

### ISSUE THREAD

**Issue by chuckleb** [overviewer/Minecraft-Overviewer#1310]
I'm running vanilla and it looks like the 1.10 texture for bone blocks are not working?

**Comment by chuckleb** [comment]
This also applies to lava blocks btw.

**Comment by CounterPillow** [comment]
Thanks for reporting this!

For anyone who wants to implement these, here's some more info:

- [Bone Block](http://minecraft.gamepedia.com/Bone_Block), ID: 216, solid
- [Magma Block](http://minecraft.gamepedia.com/Magma_Block), ID: 213, solid, emits light level 3

I might tackle those today, since they should be fairly easy to add.

**Comment by chuckleb** [comment]
To be complete, here are a few more new blocks in 1.10

- [Nether Wart Block](http://minecraft.gamepedia.com/Nether_Wart_Block), ID: 214
- [Red Nether Brick](http://minecraft.gamepedia.com/Nether_Brick), ID: 215

Thanks!

**Comment by CounterPillow** [comment]
According to the code I see here, these should already be implemented in the latest overviewer version. Are you sure your version of Overviewer and your texture pack is up to date?

**Comment by chuckleb** [comment]
You are correct, I had not loaded the correct pack when I rendered it, and then hadn't gone back to the region to force it to re-render. I just did a full render on the world and it works great. Thanks for looking into it!
