### ISSUE TITLE
Failure to generate textures when running on Ubuntu EC2 instance

### ISSUE THREAD

**Issue by stwalkerster** [overviewer/Minecraft-Overviewer#1331]
When using AWS EC2's Ubuntu AMI (ami-ed82e38e), rendering maps fails with the following traceback:
```
2016-09-28 20:23:38  Welcome to Minecraft Overviewer!
2016-09-28 20:23:38  Generating textures...
*******************************************************************************
2016-09-28 20:23:38 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 608, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 478, in main
    tex.generate()
  File "/usr/lib/python2.7/dist-packages/overviewer_core/textures.py", line 103, in generate
    tex = texgen(self, blockid, data)
  File "/usr/lib/python2.7/dist-packages/overviewer_core/textures.py", line 854, in func_wrapper
    return func(texobj, blockid, data)
  File "/usr/lib/python2.7/dist-packages/overviewer_core/textures.py", line 3387, in trapdoor
    texture = self.load_image_texture("assets/minecraft/textures/blocks/trapdoor.png")
  File "/usr/lib/python2.7/dist-packages/overviewer_core/textures.py", line 319, in load_image_texture
    img = self.load_image(filename)
  File "/usr/lib/python2.7/dist-packages/overviewer_core/textures.py", line 338, in load_image
    img = Image.open(buffer).convert("RGBA")
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2028, in open
    raise IOError("cannot identify image file")
IOError: cannot identify image file
```

This is not reproducible using the Amazon Linux AMI (ami-d41d58a7), so I suspect this is caused by an undocumented (or not included in relevant package) missing dependency somewhere.

I've put together two almost-identical scripts, one for each AMI, both of which I would expect to take a new EC2 instance and render a small map - but only the Amazon Linux one works:
https://gist.github.com/stwalkerster/4bf8f8aafa6dcb4af57939e3023df3e0

**Comment by CounterPillow** [comment]
Is zlib installed? The only way I can imagine PIL failing to load a PNG image is if zlib isn't installed, since PIL has its own (crappy) PNG decoder and doesn't use libpng.

**Comment by stwalkerster** [comment]
The Ubuntu package `zlib1g` is, but `zlibc` is not. I see there's a whole bunch of bindings for that library in the repositories for languages ranging from ghc to lua, but none for python.

I also just tried installing the zlibc package as well, but no change.

**Comment by CounterPillow** [comment]
Can you try installing pillow instead of PIL through some means, such as using pip?

**Comment by eightwiretech** [comment]
I have the exact same error since I updated my server yesterday.
Ubuntu 14.04.5 LTS
`Start-Date: 2016-09-28  15:30:41
Commandline: apt-get upgrade
Upgrade: 
bind9-host:amd64 (9.9.5.dfsg-3ubuntu0.8, 9.9.5.dfsg-3ubuntu0.9), 
liblwres90:amd64 (9.9.5.dfsg-3ubuntu0.8,9.9.5.dfsg-3ubuntu0.9), 
libdns100:amd64 (9.9.5.dfsg-3ubuntu0.8, 9.9.5.dfsg-3ubuntu0.9), 
libisccfg90:amd64 (9.9.5.dfsg-3ubuntu0.8, 9.9.5.dfsg-3ubuntu0.9), 
libssl1.0.0:amd64 (1.0.1f-1ubuntu2.19, 1.0.1f-1ubuntu2.21), 
isc-dhcp-common:amd64 (4.2.4-7ubuntu12.6, 4.2.4-7ubuntu12.7), 
libbind9-90:amd64 (9.9.5.dfsg-3ubuntu0.8, 9.9.5.dfsg-3ubuntu0.9), 
python3.4:amd64 (3.4.3-1ubuntu1~14.04.3, 3.4.3-1ubuntu1~14.04.4), 
python-pil:amd64 (2.3.0-1ubuntu3, 2.3.0-1ubuntu3.2),
python3.4-minimal:amd64 (3.4.3-1ubuntu1~14.04.3, 3.4.3-1ubuntu1~14.04.4), 
libpython3.4-stdlib:amd64 (3.4.3-1ubuntu1~14.04.3, 3.4.3-1ubuntu1~14.04.4), 
python-imaging:amd64 (2.3.0-1ubuntu3, 2.3.0-1ubuntu3.2), 
dnsutils:amd64 (9.9.5.dfsg-3ubuntu0.8, 9.9.5.dfsg-3ubuntu0.9), 
libpython3.4-minimal:amd64 (3.4.3-1ubuntu1~14.04.3, 3.4.3-1ubuntu1~14.04.4), 
isc-dhcp-client:amd64 (4.2.4-7ubuntu12.6, 4.2.4-7ubuntu12.7), 
openssl:amd64 (1.0.1f-1ubuntu2.19, 1.0.1f-1ubuntu2.21), 
linux-libc-dev:amd64 (3.13.0-95.142, 3.13.0-96.143), 
libisccc90:amd64 (9.9.5.dfsg-3ubuntu0.8, 9.9.5.dfsg-3ubuntu0.9), 
libisc95:amd64 (9.9.5.dfsg-3ubuntu0.8, 9.9.5.dfsg-3ubuntu0.9)
End-Date: 2016-09-28  15:30:46`

**Comment by CounterPillow** [comment]
>python-pil:amd64 (2.3.0-1ubuntu3, 2.3.0-1ubuntu3.2),

My best guess is that Ubuntu decided they know better than upstream and broke the PIL package. If the bug can be reproduced in a minimal python script that just loads a PNG image with PIL, then we know it's their fault and not Overviewer's.

**Comment by eightwiretech** [comment]
That is what I was thinking. 
It has been working great for months.
I will check for updates often and see if it starts working when the package gets updated.

**Comment by CounterPillow** [comment]
@agrif has identified the issue, and it indeed is with a broken and completely untested patch applied by Ubuntu. The patch in question is `debian/patches/pillow-CVE-2014-9601.patch`, applied by Emily Ratliff in pillow (2.3.0-1ubuntu3.2). agrif has added a comment to the [bug on Ubuntu's bugtracker about the findings](https://bugs.launchpad.net/ubuntu/+source/pillow/+bug/1628351).

I'll close this, since it's very conveniently not our bug. If the issue persists, please get angry at Canonical Ltd, not us.

**Comment by CounterPillow** [comment]
The problematic Ubuntu patch was now reverted by Canonical, upgrade your packages and Overviewer should work fine.

**Comment by eightwiretech** [comment]
Packages upgraded, Overviewer working.
Thank you
