### ISSUE TITLE
--genpoi not actually generating anything.

### ISSUE THREAD

**Issue by JRSofty** [overviewer/Minecraft-Overviewer#1340]
So I've created a filter for helping me identify spawners and chests in my game using overviewer. The script is attached. When I run this I would expect to see signs over the spawners when I check them in the info. This does not happen. Nor does it happen when I check the "chest" option.

I run this script in two phases 1 for rendering 2 for genpoi like so

 `overviewer.py -c /path/to/config.file`
 `overviewer.py -c /path/to/config.file --genpoi`

After the --genpoi option is ran I notice that the uuidcache.dat file has 0 bytes.

I'm pretty sure this should work, as it did on my Windows computer before. 

Information on my setup:
OS: Linux Mint Mate
Arch: 64bit
Python: 2.7.12
Overviewer: 0.12.137
Minecraft: 1.11 (when it worked on a Windows system I was using Minecraft 1.10 could be the cause?)

[Main-Mampmf.txt](https://github.com/overviewer/Minecraft-Overviewer/files/595610/Main-Mampmf.txt)

**Comment by Cynerd** [comment]
I have located problem probably. Minecraft changed it save format. New ids for example for signs it's `minecraft:sign`. This has to be changed in your configuration. But there is another change that requires overviewer fix. `Text1` on signs now doesn't contain just plain text but some, as it seems, json.
```
{"text":""}
```
So there probably must be done some changes in parsing format. It is possible that it ins't just problem just for signs.

**Comment by JRSofty** [comment]
Thanks for the heads up that 1.11 changed their saving format. That fixed mine to work the way I wanted it to. 

Maybe this should remain open for the signs portion you found, unless there is a way to work around that in python (not sure).

**Comment by Cynerd** [comment]
Well in Python you can fix it very fast. Example (not tested):
```Python
import json

... json.loads(poi['Text1'])['text']
```
It might be done even simpler. But that doesn't change that it should probably be
addressed in overviewer it self, not in configuration.

**Comment by CounterPillow** [comment]
With regards to the JSON, I'm pretty sure we've already worked around the sign JSON stuff in genPOI a long time ago. All that's different is the sign, I guess?

**Comment by Cynerd** [comment]
Yes, you are correct. I located code doing it quiet quickly. It is:
```
overviewer_core/aux_files/genPOI.py:120:                if poi['id'] == 'Sign':
overviewer_core/aux_files/genPOI.py:169:                    if poi['id'] == 'Sign': # kill me
```
So both of these should be changed to `'minecraft:sign'` if I am not mistaken. But
if I am not mistaken too, all items probably changed its name too. So probably
update also `overviewer_core/items.py` file? So create issue for support for
Minecraft 1.11?

**Comment by CounterPillow** [comment]
items.py hasn't been used in ages IIRC, I don't exactly know why we still keep it around.

Does minecraft convert the whole world to the new IDs or does it do the meme thing where it only changes the IDs of entities updated chunks? Because then that's going to be a pain to handle in the filter functions.

**Comment by Cynerd** [comment]
Well let me give you bad news. It does it exactly as you wrote it. Half of my map
has still signs because players wasn't been there. But where chunks were updater,
signs disappeared.

**Comment by CounterPillow** [comment]
Okay, so this boils down to two changes:

* Change genPOI to do the silly JSON mangling for both `minecraft:sign` and `Sign`
* Change the documentation to have a new filter function in it to apply to both `minecaft:sign` and `Sign`

This obviously is a bad solution but genPOI desperately needs a complete re-design anyway, as the current way of having people copy-paste filter functions from the docs is bad exactly for the compatibility reasons here. The only reason why I had to add the JSON workaround in the first place is because I cannot expect everyone to change their filter functions, but now we don't really have a choice unless we choose to translate all `minecraft:sign` into `Sign`, which is inevitably going to lead to problems down the road.

So I'm conflicted, do we make it easier on the users by adding a compatibility hack in the background by translating the IDs to the legacy one, or do we instead just update the docs and continue keeping it somewhat simpler by having genPOI expose the actual entity IDs in (most) cases?

**Comment by Cynerd** [comment]
I am not sure if I have something to say about it, but I would suggest to document
it and just say that there is change that breaks compatibility. Because
translating it in background is confusing specially if you access not only signs
but also other ids, then there would be "fix" for signs, but rest would be
incompatible anyway, so I see documented incompatibility as better way to handle
it.

**Comment by steveabraham** [comment]
So I've been trying to update my config to fix this, but I've maybe picked up what you guys were saying wrongly. I've changed `if poi['id'] == 'Sign'` to `if poi['id'] == 'minecraft:sign'`, but I'm still only getting signs showing that haven't been loaded since 1.11, none of the updated chunks are showing any POI.

Have I missed something?

**Comment by claym** [comment]
I rewrote the "signFilter" code that generates the signs, at least for me. Hope you can use it!

https://gist.github.com/claym/1c530332b44c1206cc1ce45f791920e1

**Comment by CounterPillow** [comment]
I've fixed this and also adjusted the documentation.

The new sign filter looks like this: 
```python
def signFilter(poi):
    if poi['id'] == 'Sign' or poi['id'] == 'minecraft:sign':
        return "\n".join([poi['Text1'], poi['Text2'], poi['Text3'], poi['Text4']])
```

Thanks for reporting this.
