### ISSUE TITLE
1.11 - Sign Text

### ISSUE THREAD

**Issue by avanrider** [overviewer/Minecraft-Overviewer#1355]
In 1.11 Minecraft sign text is no longer returned cleanly.
1.9 Text1 example: "Market District"
1.11 Text1 example: "{"text":"Market District"}"

My initial thought was that simply calling "Text1.text" would return the string "Market District" but that didn't work.

**Comment by CounterPillow** [comment]
What version of overviewer are you using?

**Comment by a2597** [comment]
version 0.12.137,
First noticed the issue on 0.12.130, but hadn't re-generated markers since 1.9, and I'm assuming the minecraft entity change in 1.10 or 1.11 is what caused the issue.

**Comment by CounterPillow** [comment]
Oops, our Windows builders broke, which is why you probably don't have the version with the fix for this in it.

We'll try to get them going again, then you can grab v0.12.145 which will fix this one. Also see #1340, which was the original issue this was reported in.

Thanks for bringing this up, I only just noticed the Windows binaries were out of date.

**Comment by a2597** [comment]
Aha! I had figured out the minecraft:sign part, but I missed that windows binary was out of date. 

Thanks!

**Comment by CounterPillow** [comment]
@eminence is looking into replacing the Windows builders with something more robust/less janky, in the meantime, Windows users of Overviewer [can compile it themselves](http://docs.overviewer.org/en/latest/building/#building-with-mingw-w64-and-msys2). Apologies for the difficulties this causes
