### ISSUE TITLE
Rendering bug

### ISSUE THREAD

**Issue by Max633** [overviewer/Minecraft-Overviewer#1369]
Hello

Before everything went well. But today render not work...

Url for my map : http://andromede-serv.eu/carte

Config.py

http://pastebin.com/eA4Z2pfM

Help me please

Thank you

**Comment by CounterPillow** [comment]
You have a chunk that's very far away from the rest of the map, if you zoom in you can still see it.

Try looking into the regions directory and looking for a .mca file with really big coordinates in the file name. Removing that file (but making a backup of it just in case it's the wrong one), and then rendering the map again should fix it.

Alternatively, since your world has a border, you can use the crop setting to limit the map's rendering to a certain area.

**Comment by Max633** [comment]
Ok thank you, it is all good now

**Comment by CounterPillow** [comment]
Glad to hear that fixed your issue.

Oh and by the way, when asking for help in our IRC channel, please stay for longer than just 1 minute. You've already left by the time I saw your message.

**Comment by Max633** [comment]
Hi,

It starts again ... The chunk are generated alone or else?

Thank you

**Comment by CounterPillow** [comment]
they might be generated by Minecraft due to a bug, or by a player teleporting.

I recommend you use the `crop` option to avoid having to keep deleting those chunks.

**Comment by Max633** [comment]
This option allows the person to see the minerals on the sides ...

Is it possible to set a default zoom? How to do? 

"defaultzoom": 1, not work...

Thank you
