### ISSUE TITLE
Question: How to skip rendering most zoomed in state?

### ISSUE THREAD

**Issue by andrewkm** [overviewer/Minecraft-Overviewer#1379]
I'm trying to limit the amount of space used after my render. Map size is 11 GB even with nerfed image quality. Is it possible to eliminate specific zoomed in levels of the render process. My goal would be not to render the most zoomed in state.

Sorry for posting on github, really don't know where to go to ask questions.

**Comment by CounterPillow** [comment]
Sadly this can't be done, since Overviewer renders from the most zoomed in state outwards. You can modify the resulting overviewerConfig.js to limit the number of zoom levels the map lets you zoom in, and then use a script to delete the deepest level of the quadtree, but that means you'll have to re-render the entire map every time you want to update it.
