### ISSUE TITLE
map bounds feature is not working on production server, but it is working when i run it locally

### ISSUE THREAD

**Issue by hetal393** [overviewer/Minecraft-Overviewer#1393]
I am using google maps api v3 javascript.
Please Help !!

**Comment by CounterPillow** [comment]
This is a repository for Minecraft-Overviewer, not the Google Maps API. Are you sure you're in the right place?

**Comment by CounterPillow** [comment]
Closing this for a few reasons:
 
- Probably not an Overviewer issue but someone just opening an issue wherever
- if it is an Overviewer issue, the reporter did not elaborate on what they meant and did not provide their config file and Overviewer version

if this is an Overviewer issue, then please provide

- the version you're using
- your config file
- ideally also a link to your map

or otherwise I won't even bother to re-open it.
