### ISSUE TITLE
Can't take screenshots using Firefox or Chrome command-line

### ISSUE THREAD

**Issue by jones77** [overviewer/Minecraft-Overviewer#1436]
I've used both Firefox and Chrome in headless mode to try and take screenshots of my overviewer map (I'd like to create some thumbnails).  The screenshots come up blank / black.

When I load the site in my browser normally I can see that little warning message before the actual map loads ("If you can see this message...") but then it properly loads the map.  Is there any way to by-pass that?  Wondering if that is causing issues.

FWIW Taking screenshots of Google Maps works fine.

    google-chrome-stable --no-sandbox --headless --disable-gpu --screenshot URL
    firefox -screenshot screenshot.png -url URL -window-size=1024,1024

**Comment by CounterPillow** [comment]
Dunno, but that seems like a really hacky way to go about things anyway. Why not use [png-it.py](https://github.com/overviewer/Minecraft-Overviewer/blob/master/contrib/png-it.py)?

**Comment by jones77** [comment]
Heh, I'd argue it's decoupled. :-)

Did wonder if there was something built-in.  I'll check that out.  (Feel free to close this ticket.)

**Comment by CounterPillow** [comment]
Now that we've switched to leaflet, you at least get the UI controls, but still no tiles, because those are loaded in dynamically based on your coordinates. There's not much we can do about this, and even if we could, it wouldn't be worth the effort.

Do keep in mind that you can just use the farthest-zoom-level PNG image from your output directory as a preview. So there are like a million better ways to get a preview of a map that don't involve launching an entire web browser in headless mode.
