### ISSUE TITLE
Memory Problem Using png-it.py

### ISSUE THREAD

**Issue by NPCtom** [overviewer/Minecraft-Overviewer#1503]
I am trying to convert a world  rendered using Overviewer to a PNG image using png-it.py which can be found [here](https://github.com/overviewer/Minecraft-Overviewer/blob/master/contrib/png-it.py).

Unfortunetly when I run the command `>python C:\Users\npctom\Desktop\png-it.py -m 90000 -z 8 -o Y:\ C:\Users\npctom\Desktop\mzrender\world-lighting` it outputs this error:

```
The image size will be 98304x98304
A total of 36864 MB of memory will be used.
Traceback (most recent call last):
  File "C:\Users\npctom\Desktop\png-it.py", line 212, in <module>
    main()
  File "C:\Users\npctom\Desktop\png-it.py", line 134, in main
    final_img = Image.new("RGBA", final_cropped_img_size, (26, 26, 26, 0))
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2350, in new
    return Image 
MemoryError
```

I am using this on a VM and have dedicated 4GB of RAM to the VM. I have allocated 35GB of RAM using the -m option as anything less than what is required will show this error:

```
The image size will be 98304x98304
A total of 36864 MB of memory will be used.
Warning! The expected RAM usage exceeds the specified limit. Exiting.

```
Is there any way to use only up-to 4GB of memory using this script?

**Comment by CounterPillow** [comment]
No, because a big bitmap will need a lot of memory, and unless unreliable hacks are used, you'll need to decode the entire image to even view a small section of it. This is why very large images aren't used in the first place.

You can do some calculations yourself; when decoded, an 8-bits-per-channel RGB image will use 3 bytes per pixel. The 98304*98304 image will require 28991029248 bytes of memory when decoded, or about 27 GiB.
