### ISSUE TITLE
[Leaflet CSS] Styling is missing for region info in the bottom left corner

### ISSUE THREAD

**Issue by mtoensing** [overviewer/Minecraft-Overviewer#1518]
![image](https://user-images.githubusercontent.com/136737/53187323-2ed4a380-3603-11e9-9aa8-7ed0f9488f3f.png)
This should look like this: 
![image](https://user-images.githubusercontent.com/136737/53187358-44e26400-3603-11e9-82c8-7aa64e30b319.png)
This was the case before the merge of 113 into master.

**Comment by CounterPillow** [comment]
Works for me. What browser are you using?

**Comment by mtoensing** [comment]
Chrome of course. Master branch.

**Comment by mtoensing** [comment]
I will delete my old copy and pull a fresh master branch for my docker image. I’ll report back

**Comment by CounterPillow** [comment]
Can't reproduce in Chromium 72.0.3626.109 either.

**Comment by mtoensing** [comment]
I removed everything and I copied the master branch again. Problem solved. Sorry. Is there some kind of basic docker image you use so I can use that so that we are on the same page regarding the environment?

**Comment by CounterPillow** [comment]
>Is there some kind of basic docker image you use so I can use that so that we are on the same page regarding the environment?

No. I don't use docker, so there isn't a docker image you could use to be on the same page as I am. I also would never run docker myself because 1. I know my environment, and can easily adjust it myself without any bloated container abstraction if needed 2. I don't like docker, because it just makes everything needlessly difficult and seemingly makes people forget what version of a software they're running.

**Comment by mtoensing** [comment]
Ok. So there is no chance that We could put a dockerfile in the root of the repository (like this one https://github.com/mtoensing/Docker-Overviewer-1.13.X/blob/master/Dockerfile) and reference the files in master branch for the copy command and everyone would be able along with some config.py examples to start right away?

If not, could you at least tell me if my python setup in the dockerfile ist ok? 

And if you see a chance I could prepare a merge request for the idea with the dockerfile in the official repository :) this would even be dockerhub compatible.

**Comment by CounterPillow** [comment]
>So there is no chance that We could put a dockerfile in the root of the repository

Considering how hopelessly outdated the dockerfiles for our automatic builders are, I don't think this would go well.

In your dockerfile, I don't know what `Minecraft-Overviewer-minecraft113-fixed` is, and that's where your issues are coming from, because if you're using a custom branch you're not running the same code as I am running on master.

I don't see the point of dockerhub when we have distro packages and repositories for almost every major distro, which integrate better and are easier to use than any docker image could ever be.

**Comment by mtoensing** [comment]
Minecraft-Overviewer-minecraft113-fixed is the master branch since your merge. That’s because I ask if we could just add a or my dockerfile to the repository (with a few changes of course) that uses the files in the master branch. I could build a mehr request for that - or I continue to maintain my repository that will from now on use the master branch
