### ISSUE TITLE
Support PyPy

### ISSUE THREAD

**Issue by totemo** [overviewer/Minecraft-Overviewer#1555]
I can't find any documentation on running Minecraft Overviewer under `pypy`, nor can I find any issues pertaining to PyPy compatibility, or mention of relevant commits in the output of `git log`. So I thought it might be helpful to open an issue as a breadcrumb for fellow travellers.

I've tested running under `pypy` and got:

    Something has gone wrong importing the c_overviewer extension.  Please
    make sure it is up-to-date (clean and rebuild)

The only explicit mention of PyPy I can find in the Overviewer docs is [Overviewer V2 (with oil) Design](http://docs.overviewer.org/en/oil/design/oil/). That document also mentions concerns over PIL and numpy dependencies that apparently, according to the [PyPy FAQ](doc.pypy.org/en/latest/faq.html), can work with PyPy.

By my reckoning, Overviewer's performance degraded by a factor of about 18 times in the 1.13.2 version, when compared to its performance on 1.12.2 maps. I see that some of that has been clawed back since January 2019 (a factor of about 2.8x based on a small (416x416) test area). Still it would be really nice to get some of the purported [7x speedup](https://www.techrepublic.com/article/python-programming-language-gets-speed-boost-from-latest-pypy-interpreter/) possible with PyPy.

So my questions are:

 * Can you confirm that it's currently not possible to run Overviewer with PyPy?
 * What's left to do support PyPy? If someone reimplemented the `c_overviewer` package with [CFFI](http://doc.pypy.org/en/latest/extending.html#cffi) would that be all, or would there be other issues to solve?

**Comment by CounterPillow** [comment]
>Can you confirm that it's currently not possible to run Overviewer with PyPy?

It currently is not possible to run Overviewer with PyPy.

>What's left to do support PyPy?

I don't know, but aside from the C extension you'll also want to make sure multiprocessing works with PyPy.

>Still it would be really nice to get some of the purported 7x speedup possible with PyPy.

I'd be very surprised if PyPy reaches 7x speedup, considering the last time I've tried PyPy on a project it actually made things slower due to abysmally slow string joins, but obviously this is heavily dependant on the workload at hand.

Current focus is getting everything ready to merge the Python 3 branch, so there's no desire to look into PyPy from my side at this time.

**Comment by totemo** [comment]
Okay, thanks for the reply.

**Comment by agrif** [comment]
Just as a short clarification: at the time we last looked at numpy (and the last time we wrote anything about it, which you found) neither `PIL` nor `numpy` worked under pypy. Since then, that support has been added. I don't think any of us have specifically looked at what would be needed since then, though.
