### ISSUE TITLE
Incorrect blocks rendering in some places

### ISSUE THREAD

**Issue by ace-savant** [overviewer/Minecraft-Overviewer#1578]
Apologies if this issue is a duplicate, or a known issue. I have been trying to track down the source of this problem. It appeared shortly after I used the early revisions of Overviewer made for 1.13. 

In the attached image, you'll see some strange tile choices for the sides of a building that in reality are all the same (the black concrete building is completely black concrete, and the smooth red sandstone with smooth sandstone stripes has a contiguous and repeating pattern).

I've tried a number of things to address this, including running an entire render from scratch, and I'm out of ideas as to what to try next. Is there a chance anyone here can help me?

The server is running 1.13.2 vanilla, no mods of any kind.

![ErrorExample](https://user-images.githubusercontent.com/51167816/58568884-b2052700-81fa-11e9-96b0-aa0b56e097c7.png)

**Comment by CounterPillow** [comment]
What version of Overviewer is this? Can you show me an in-game screenshot of the area?

**Comment by ace-savant** [comment]
This was rendered with Overviewer version 0.13.88. Attached is a screenshot
of the actual area.
[image: 2019-05-29_13.10.27.png]

**Comment by ace-savant** [comment]
![2019-05-29_13 10 27](https://user-images.githubusercontent.com/51167816/58580674-44b1c000-8213-11e9-86b2-17b24f4d53b6.png)

**Comment by supergnaw** [comment]
I am also having this issue. I can't say for sure if there is any correlation but when a chunk is recently updated, the rendered chunk appears to be incorrect as though it's just the wrong chunk. Subsequent renders will be correct. Perhaps this is caused by the server updating the chunk while the renderer is processing the data.

**Comment by supergnaw** [comment]
![overveiwer_errs1](https://user-images.githubusercontent.com/25543199/58805804-c52b5300-864f-11e9-88b3-dd334955ceae.PNG)
![overveiwer_errs2](https://user-images.githubusercontent.com/25543199/58805811-c8264380-864f-11e9-9e71-b296f4c17ca0.PNG)
These were the errors I got while rendering a live server. I noticed that the errors were typically near where someone was building. I have since added a script to stop the server to create a new backup of the live map, then render from the backup directories rather than the live worlds. Although I have only tested this for a few hours it appears to have mitigated the issues. As stated previously, I suspect this being the result of Overviewer rendering a map while chunks are still being updated.

**Comment by ace-savant** [comment]
In my case, I already render from inactive backups, so the issue I have may be different from the one you are having.

**Comment by CounterPillow** [comment]
>These were the errors I got while rendering a live server.

Yeah, this is a known issue and unrelated to the original post.

**Comment by ace-savant** [comment]
If there is any additional information I can provide or context, please let me know.

**Comment by jobe1986** [comment]
I've also been getting the same issue since 1.13, but it is still present in overviewer "0.13.90 (522ee28)" with minecraft 1.14.2. It seems to be replacing blocks of one type with another in the render process.

Referencing for example: https://mc.simplanet.org/index.html#/8489/64/30/max/Simplanet%20-%20overworld/day
To the east of the purpur roofed building there is a line of sand with a trapdoor that isn't there in game, it should be grass and only a single block of sand matching the pattern of the path. And to the south there are an additional 2 blocks of sand that again aren't there in game.

This is what the same area looks like in game:
![2019-06-16_14 33 28](https://user-images.githubusercontent.com/1899593/59564877-e1fa5a00-9043-11e9-9088-abfee6004301.png)

I have also noticed that the misplaced blocks there are limited to within a single chunk at that location. But there are other affected chunks around the world.

**Comment by Dravere** [comment]
I'm not sure, but I might have this problem as well. In my case I create the map from a backup for the world. The backup is from the live server. But before the backup is done, a `save-off` and `save-all flush` is executed first. Only after the backup is finished a `save-on` is sent.

To make sure this has nothing to do with backups from a live server, I downloaded the backups of the map today and first ran it on a local server then shut the server down properly. Only then I ran Overviewer on the map. I got the same errors again. Then I converted the map into a single player world and took a look at it in-game. No blocks were misplaced in the world, everything was normal. I shutdown Minecraft and ran Overviewer on that single player world and there still were all the errors in it.

Some examples of those errors (marked with arrows):
![overviewer-error-01](https://user-images.githubusercontent.com/2047920/69903660-d48c1e80-139c-11ea-9568-7a870c7e0d60.png)
Those signs shouldn't be there.

![overviewer-error-02](https://user-images.githubusercontent.com/2047920/69903666-e077e080-139c-11ea-8ba2-4797bd4446a0.png)
Somehow a line of blocks gets duplicated.

![overviewer-error-03](https://user-images.githubusercontent.com/2047920/69903669-ea99df00-139c-11ea-9f77-1f35ae75c20c.png)
Those stairs appear out of nowhere.

![overviewer-error-04](https://user-images.githubusercontent.com/2047920/69903677-f71e3780-139c-11ea-8b16-694db0fd1f4d.png)
Chests and slabs appear out of nowhere in the ground.
