### ISSUE TITLE
AuthenticationError

### ISSUE THREAD

**Issue by zwang20** [overviewer/Minecraft-Overviewer#1586]
I was running the program in command prompt when I encountered the following issue
![Screen Shot 2019-06-19 at 10 32 21 AM](https://user-images.githubusercontent.com/41721295/59728490-9b903f80-927d-11e9-97a0-0269657548d3.png)

**Comment by agrif** [comment]
This looks like a multiprocessing bug. [Here's the relevant bits of Python source](https://github.com/python/cpython/blob/2.7/Lib/multiprocessing/connection.py#L416-L439). Note that this error only happens if the two sides of the connection can't agree on an HMAC digest.

Are you running our pre-built packages? What platform? And what version (`overviewer.py --version` or `overviewer.exe --version`) ?

**Comment by CounterPillow** [comment]
This might also legit be caused by bad RAM if the error is intermittent

**Comment by CounterPillow** [comment]
Please let us know if this still is an issue in Overviewer 0.14 or newer, and we'll re-open it.
