### ISSUE TITLE
How to speedup the startup?

### ISSUE THREAD

**Issue by alex4200** [overviewer/Minecraft-Overviewer#1604]
Whenever I (re-)start a render, because the previous render has not finished (and I require the mac for something else), the following two items are run:

- Generating textures (takes about 5 minutes)
- Preprocessing (takes about 10 minutes). 

Is there a way to speed up these steps? Can the textures be save somwehere, instead of generating them anew all the time? 
And what does the 'Preprocessing' step do? Can that step be improved?

**Comment by CounterPillow** [comment]
>Is there a way to speed up these steps? Can the textures be save somwehere, instead of generating them anew all the time?

One change we could make is to generate the textures lazily, but usually the generating textures stage takes no more than 30 seconds even on my ultrabook laptop. I'm not sure what's going on with your system for this to take an entire 5 minutes.

>Preprocessing (takes about 10 minutes).

This step scans all chunks to see which ones are "dirty", i.e. need re-rendering. On operating systems where mtimes are reliable (i.e. not Windows) we only scan the chunks in region files which have a newer modification time than the last finished (I think?) render. The scanning itself just involves reading the chunk's modification time out of the NBT structure, so there is no hard processing to be done, just a lot of NBT parsing.

I'd rather not cache the generated textures because they should be a fast fixed-time expense, and caching them would involve keeping a cache somewhere on the filesystem (either OS-specific or in the output dir) and then managing versions of the cache should we make changes to the textures.py code of Overviewer.

Going forward I'd rather look into the following two things:
1. see if there are any optimisations to be made in the preprocessing step, potentially optimising the NBT loader if needed.
2. rewrite Overviewer's texture generation completely with a block model renderer that processes things lazily, so that a texture for a block is only rendered once it's needed, and then kept for the duration of the program run time.

**Comment by CounterPillow** [comment]
I've fixed a bug in the texture image loading cache logic that brings texture generation down to about 14 seconds on my system.

**Comment by CounterPillow** [comment]
I've done some more cleanup of old shitty code, which has reduced the texture generation for me from 14 seconds to 9 seconds. It has an even bigger impact if you were using a manually specified texture path.

I'll consider this resolved for now, because after a quick glance at the preprocessing logic I could not yet find any obvious mistakes.
