### ISSUE TITLE
Access minecraft server files via ftp

### ISSUE THREAD

**Issue by zacthespack** [overviewer/Minecraft-Overviewer#1712]
Couldn't find this mentioned anywhere at all but I wonder if there is any thought given around building ftp access into the app. I have a number of small minecraft servers which I would rather not run overviewer on. 

Instead of would love to be able to connect to these servers via ftp and then use my desktop to render the maps. Currently i zip the world and download it which is fine but doesn't do a good job at preserving created/updated file timestamps.

**Comment by chungy** [comment]
I would recommend mounting your server files locally somehow; NFS (or CIFS/SMB) would be ideal, but sshfs can do in a pinch. ftp itself is pretty outmoded these days.

It'd be complicated to have some kind of network access in overviewer itself and I think it's the wrong place to even try it.

**Comment by Wunkolo** [comment]
Overviewer's end-product is ultimately just a bunch of static files that are ready to be served. So it's not really in overviewer's place to be anything more than a "renderer" that spit out files. Everything around transporting the files and reading files and such is kind of _around_ Overviewer and there is plenty of tooling around such a thing.

I would recommend using something like `rclone` or `sshfs` so that you can sync/mount your remote minecraft server's map files and then run the render on your more-powerful machine where then you can upload to be statically served upon a web page.
At the very least, with `rclone`, it will optimally only download or upload the files that have changed between the two file systems and will greatly optimize both your map-download and your render-upload and it will preserve the file timestamps as well.

**Comment by CounterPillow** [comment]
Either mount those remotes using something like a FUSE mount or use rsync to continually sync the files locally. Accessing remote file systems really isn't within the scope of Overviewer.

Plain-text FTP is so hilariously insecure and outdated nobody should be using it anymore btw.
