### ISSUE TITLE
Automating builds

### ISSUE THREAD

**Issue by misuzu** [overviewer/Minecraft-Overviewer#1715]
I'm having an issue building Overviewer under NixOS:
`overviewer_core/src/overviewer.h:40:10: fatal error: Imaging.h: No such file or directory`
At first i thought it's a [Pillow issue](https://github.com/python-pillow/Pillow/issues/4400), but Pillow maintainers seem to disagree. Maybe there is some solution to building from source that doesn't include hacks to Pillow (manually coping headers, patches in distributions packages)? Suggestion to bundle required headers with Overviewer seems reasonable.
If this is fixed then maybe Overviewer can be installed using pip even.

**Comment by CounterPillow** [comment]
Most distributions include the header in their pillow package. For as long as we use Pillow we will rely on the Imaging.h header. No, asking *us* to bundle a header that is part of *their* library and is version specific (they broke the ABI before!) is not reasonable at all.

**Comment by dansgithubuser** [comment]
Having this issue and not clear what the solution is. Your docs: "If you choose to install pillow through pip instead of your distribution’s package manager, you won’t get the pillow headers which Overviewer requires to build its C extension. In that case, you should manually download the header files specific to the version of pillow you installed, and point at them with the PIL_INCLUDE_DIR environment variable. A version mismatch between the installed pillow library and the headers can lead to segfaults while running Overviewer due to an ABI mismatch."

I did install with my distribution's package manager, so I should have the pillow headers, right?

So the workaround is to install with pip and hope I get headers that way?

At a different level, I'm surprised your attitude is:
1) The private header is OK to use as if it were public because it is distributed, in your experience.
2) MC Overviewer should _not_ do extra packaging that would solve ABI compatibility issues.

Much appreciation for this tool. I'll get back with a workaround if I find one.

**Comment by dansgithubuser** [comment]
Workaround: clone the pillow repo and point `PIL_INCLUDE_DIR` to the path containing `Imaging.h`.

Seems like it'd be real easy to add Pillow as a submodule to this repo.

**Comment by CounterPillow** [comment]
Why would we add it as a submodule? We don't depend on a specific version of Pillow. Your binary of Pillow will depend on a specific version of the Pillow headers, but we don't know what version this binary is.

> The private header is OK to use as if it were public because it is distributed, in your experience.

Yes.

> MC Overviewer should not do extra work that would solve ABI compatibility issues caused by using a private header.

The extra work would be not using Pillow, as using these headers is the only way to directly use Pillow from the C extension, which is what we need to do, unless you're suggesting that we do a roundtrip through python for every single imaging call so that you are less mildly inconvenienced when running setup.py for the first time.

Could we rely less on internal structs and use accessor functions instead of they are provided? Maybe, I haven't really looked into it, but we'll still need to use actual imaging functions from C, which is something Pillow does not want to support officially. However, I will not be maintaining a horrible preprocessor infested vendored all-versions-forever-have-fun-keeping-it-working-in-the-future Pillow header just because you chose to use CentOS. That is my attitude.

**Comment by dansgithubuser** [comment]
"Why would we add it as a submodule?" So that you can guarantee a version of Pillow that works with MC Overviewer, and expose the private `Imaging.h`. Aside from fixing this issue, if Pillow makes any breaking change, you can continue as if nothing happened until you want to update. I am naive to the complexity of building Pillow.

"We don't depend on a specific version of Pillow." How can you not? Pillow makes no guarantee about `Imaging.h`, so you depend on whatever version(s) of Pillow have an `Imaging.h` that works with your source, that is also available to yours users in a method described in your docs. For me that is no version, hence the need for workaround, and desire for real solution. I use Lubuntu Bionic Beaver, which I think is mostly similar to Ubuntu Bionic Beaver in terms of packages, but I'm not 100% sure.

Why do you think it's OK to use a private header as if it's public just because it is distributed in your experience? It's the same as if I demanded MC Overviewer to do my taxes. Simply not a feature. I want to get on the same page that this isn't a normal thing to do, so I can understand why this choice was made. I'm happy to contribute a change to docs to cover this a little better.

As for alternatives to Pillow, I doubt the momentum is worth shifting at this point; Pillow is what MC Overviewer uses. If we are talking about architecture though, I'm curious why Pillow was selected instead of a C lib?

I am 0% asking you to work on something you don't want to. But help the people coming across this issue think of good solutions. We could help if we had a better answer than "Pillow doesn't have a feature that would make this easy". Or at least we'd read through this issue and stop bothering you :wink:

**Comment by CounterPillow** [comment]
> "Why would we add it as a submodule?" So that you can guarantee a version of Pillow that works with MC Overviewer, and expose the private Imaging.h. Aside from fixing this issue, if Pillow makes any breaking change, you can continue as if nothing happened until you want to update. I am naive to the complexity of building Pillow.

What issue? Pinning a version of Pillow is an extremely bad idea. They frequently publish security fixes, so any vendored version we have through submodules would quickly become dangerously obsolete and need constant attention. Distributions, on the other hand, take care of things like this, and ship us with a version of Pillow that just works, provided your distribution is not awful.

> "We don't depend on a specific version of Pillow." How can you not? Pillow makes no guarantee about Imaging.h, so you depend on whatever version(s) of Pillow have an Imaging.h that works with your source

Buddy this project is like 12 years old now and at no point have we ever had to deal with a Pillow API break. Only ABI. We are not fucking vendoring Pillow because of you. The reality is that we indeed do not depend on a specific version of Pillow; literally every single one of them works, no matter what you're claiming.

> Why do you think it's OK to use a private header as if it's public just because it is distributed in your experience?

Because it's the best solution to use Pillow from within a C extension. The alternatives are:

- vendoring *all of Pillow*, bad idea as outlined above
- writing our own header file that is basically just an amalgamation of all header files Pillow ever shipped
- accepting a massive slowdown by going through Python instead of using C calls directly

And we'd be choosing any of these subpar solutions to fix what exactly?

> If we are talking about architecture though, I'm curious why Pillow was selected instead of a C lib?

Because, unsurprisingly, we also use Pillow from within Python. So we'd need Python bindings anyway.

> I use Lubuntu Bionic Beaver, which I think is mostly similar to Ubuntu Bionic Beaver in terms of packages, but I'm not 100% sure.

Ubuntu Bionic ships the headers: https://packages.ubuntu.com/bionic/amd64/python3-pil/filelist So I don't really know what you were doing to even mess this up.
