### ISSUE TITLE
Option to disable root warning

### ISSUE THREAD

**Issue by astronouth7303** [overviewer/Minecraft-Overviewer#1719]
A feature to disable the root warning message.

There are contexts (namely running inside a container) where running as root is perfectly and expected, and the warning is just noise.

The warning is:
> You are running Overviewer as root. It is recommended that you never do this, as it is dangerous for your system. If you are running into permission errors, fix your file/directory permissions instead. Overviewer does not need access to critical system resources and therefore does not require root access.

IMHO, this should be settable from envvar or config file.

**Comment by CounterPillow** [comment]
>There are contexts (namely running inside a container) where running as root is perfectly and expected

I disagree, even in containers processes shouldn't be run as root because the slightest misconfiguration or Linux namespaces bug could give the process root rights on the host. You can easily set a uid and gid with e.g. docker by running with `--user UID:GID`.

The root user in your container is the same root user as on your host machine, it's just restricted by (configurable) capabilities. Following the principle of least privilege to accomplish a task, having the container use the root user is suboptimal.

[Docker's documentation](https://docs.docker.com/engine/security/userns-remap/) itself states:

>The best way to prevent privilege-escalation attacks from within a container is to configure your container’s applications to run as unprivileged users.

(Since Overviewer doesn't require root privileges, no remapping needs to be done, you can just start the container as a non-root user)

**Comment by astronouth7303** [comment]
I'm also running these containers rootless (via podman), so root inside the container is my regular user on the host.
