### ISSUE TITLE
overviewer.js:169 Fetch API cannot load file://progress.json. URL scheme must be "http" or "https" for CORS request.

### ISSUE THREAD

**Issue by Zyercas** [overviewer/Minecraft-Overviewer#1725]
So, the whole render process goes smoothly. Here's the output with the --verbose argument: https://pastebin.com/DQNzPjBQ

but then when I try opening the index.html this is what happens: 

![image](https://user-images.githubusercontent.com/35607941/74565146-dbc0d280-4f70-11ea-8826-b352577c5a55.png)

I tried rendering a different world and the same thing happend. I looked into chrome's console and in both cases this is what was being logged: 

![image](https://user-images.githubusercontent.com/35607941/74565131-d19ed400-4f70-11ea-86ef-a60c03b51021.png)

So, what's the problem? Did I do something wrong?

**Comment by CounterPillow** [comment]
That error message isn't what's causing this, this is normal if you're not using the JSObserver.

The actual problem is this:

>Just letting you know, your map requires 17 zoom levels. This is REALLY big!

You have a small world, but something, likely Minecraft, generated a very far away chunk. This results in your resulting render being really zoomed out. There's two ways you can solve this:
1. go into your worlds region folder, move the region with really out of whack coordinates in its filename out of it. It likely only contains garbage unless you really teleported far away.
2. or you can use the crop option in an overviewer config file
