### ISSUE TITLE
Publish on pypi

### ISSUE THREAD

**Issue by remcohaszing** [overviewer/Minecraft-Overviewer#1733]
I want to use minecraft overviewer a try on Ubuntu 19.10 and ran into #1595.

I tried installing it using [pipx](https://github.com/pipxproject/pipx).

```sh
sudo apt install pipx
pipx install pipx  # upgrade for git repository support
pipx install git+https://github.com/overviewer/Minecraft-Overviewer.git
```

However this failed, because `setup.py` depends on numpy.

---

Could you publish this package on pypi as wheels for various Python versions and an sdist? This way all standard Python tooling can work with it. I.e.:

```sh
pip install --user minecraft-overviewer
pipx install minecraft-overviewer
pipenv install minecraft-overviewer
poetry add minecraft-overviewer
```

This would also fix support for unsupported platforms, offering a nice workaround for #1595. `pipx` can be mentioned as a platform independent installation method in the readme.

**Comment by enaut** [comment]
it is way easier to install numpy using apt:

```
sudo apt install python3-numpy 
```

Also there is a ubuntu package of overviewer: https://overviewer.org/downloads

**Comment by CounterPillow** [comment]
We won't do this because the C extension depends on non-public Pillow headers which most distros ship but pypi doesn't ship, so automatically building from source with pip et al wouldn't work. Furthermore, if someone had the time to add automated wheel builds (which would require us to build against ancient versions of libc because someone might be running some ancient RHEL or whatever, ew) they could just as well simply fix the debian repos to build things for different versions of python.
