### ISSUE TITLE
[Bug] Strange region files in Minecraft 1.16 cause Overviewer to always render the overworld map with 22 zoom levels

### ISSUE THREAD

**Issue by whalehub** [overviewer/Minecraft-Overviewer#1821]
**Environment**
- **OS:** Debian 10
- **Minecraft:** PaperMC 1.16.1 (build 131)
- **Python:** 3.7.3
- **Java:** 11.0.8
- **Overviewer:** fcb3f26

**Problem Description**
I'm not sure whether this issue is specific to PaperMC or whether Spigot, Bukkit and/or the official Minecraft server implementation are affected as well, but I've noticed that Minecraft has been generating strange region files ever since the release of 1.16. The coordinates for them are so huge that even a fully rendered Minecraft world would not come close to displaying them.

The file for a region that is quite far away from the spawn point is typically in the double digit range, like `r.15.-10.mca`. The strange region files meanwhile are all in the four to five digit range, such as `r.-2372.-8040.mca` or `r.-20878.-52070.mca`. As long as even one of these files is present in the `world` directory, Overviewer will render the overworld map with 22 zoom levels which ends up looking like a completely blank map until you zoom really, really far in.

If these files are deleted prior to starting a render, the map looks perfectly fine. Minecraft will always regenerate them after restarting the server, so it's a bit annoying to manually delete them prior to each render.

You can download a zip file that includes one normal and one strange region file here: [regions.zip](https://github.com/overviewer/Minecraft-Overviewer/files/5020993/regions.zip)

**Proposed Solution**
I think the easiest fix would be for Overviewer to ignore these region files the same way it ignores zero-size region files (a3e4812).

**Additional Info**
I've had a look at the strange region files with [NBTExplorer](https://github.com/jaquadro/NBTExplorer) and noticed that they are structured differently than normal region files.

Here's what a normal region file looks like, for reference:

![normal](https://xbb.datahoarder.dev/VUSu3/lUmOnEkE41.png/raw)

And here's what all the strange region files look like:

![strange](https://xbb.datahoarder.dev/VUSu3/xEQufUCO66.png/raw)

**Comment by whalehub** [comment]
These strange region files seem to have existed for much longer than 1.16 since someone reported the same issue with them back in 2012 (#801), although they were using Bukkit.

**Comment by LeadMagnet** [comment]
I remember this well....in MC 1.12 Bukkit had a real problem with "ghost" region files. The problem manifested when switching back and forth from Spigot and Bukkit. Fairly sure they identified what the problem was and corrected it. I haven't noticed this on my Spigot server, although I no longer switch between Spigot/Bukkit and the current 1.16 world is brand new.

If the regions are not active, have you tried just deleting them and see if they return?

**Comment by whalehub** [comment]
@LeadMagnet Yes, unfortunately Minecraft always regenerates these files after a server restart if I delete them. It's interesting to note that the regenerated files are always named differently than their deleted counterparts.

**Comment by CounterPillow** [comment]
This isn't a new thing, Minecraft loves generating these sometimes and since we can't tell the difference between someone just having a far away nether portal/tp and Minecraft doodoo your best bet is to either delete them yourself or use a crop.

Trying to detect them based on various attributes that indicate they're not fully generated yet just leads to more issues with people complaining that certain chunks they expect to show up don't show up, etc.
