### ISSUE TITLE
[Support] genPoi assistance

### ISSUE THREAD

**Issue by LeadMagnet** [overviewer/Minecraft-Overviewer#1823]
Alrighty....been staring at this for a couple of days and need a new pair of eyes!

I'm trying to get a list of manual POI's into the render without success. The rendering process is fine (excluding missing nether blocks) and the map is as you would expect, but everything I've tried to get manual POI's into the map has failed.

Here's the config file I'm using

```
worlds["world"] = "C:/MCdata/world"

manual_locations = [
    {
    'id':'Warps',
    'x':0,
    'y':65,
    'z':0,
    'name':'Spawn City'
    },
    {
    'id':'Warps',
    'x':-1720,
    'y':73,
    'z':179,
    'name':'Ice Spikes'
    },
    {
    'id':'Player Bases',
    'x':-117,
    'y':99,
    'z':-196,
    'name':'OCE Main Base'}
]

def warpFilter(poi):
    if poi['id'] == 'Warps':
        return poi['name']

def playerbaseFilter(poi):
    if poi['id'] == 'Player Bases':
        return poi['name']
        
renders["world"] = {
    "world": "world",
    "title": "Overworld",
    "rendermode": smooth_lighting,
    "dimension": "overworld",
    'manualpois': manual_locations,
    'markers': [dict(name="Warps", filterFunction=warpFilter, icon="markers/marker_anvil.png"),
                dict(name="Player Bases", filterFunction=playerbaseFilter)],
}
outputdir = "C:/inetpub/wwwroot/worlds"
```

The command I'm executing is 

```
overviewer.exe -c MCServer_config.py
overviewer.exe -c MCServer_config.py -genpoi -skip-scan
```

Does anyone see where I've gone wrong?

Thanks!

**Comment by Hraefin** [comment]
That looks fine.  On my config I don't have a separate list for manual pois, I just have them in the main render.
e.g.
instead of 

'manualpois': manual_locations,

I have, for example

'manualpois':[{
    'id':'Warps',
    'x':0,
    'y':65,
    'z':0,
    'name':'Spawn City'
    }],

I have noticed that the browser will not always render updates properly until you clear the image cache.  
First make sure the map page isn't loaded in the browser, then:

In Chrome, Settings/Privacy_Security/Clear Browsing Data/cached images and files.  I would ONLY clear images and files so as not to mess up other things.  Then restart chrome and see if you get the proper markers.

Also check to be sure your markers are enabled on POI pane on the right side of the map.

**Comment by LeadMagnet** [comment]
@Hraefin thanks for that.

I orginally had the manual list inside the reder call. That didn't work either.

Been bouncing back between Edge, Opera and Blaze with little effect in normal and private modes so that should address the cache issue.

I never get the POI pane. Almost like it's not reading it at all. Never get any errors. I'll do a verbose render tonight and see what it reports.

**Comment by CounterPillow** [comment]
```
overviewer.exe -c MCServer_config.py -genpoi -skip-scan
```

You need to use double dashes for long options, i.e.

```
overviewer.exe -c MCServer_config.py --genpoi --skip-scan
```

this is a quirk with overviewer's argument parsing whereby it just ignores stuff it doesn't know.

**Comment by LeadMagnet** [comment]
that did the trick! Thanks @CounterPillow
