### ISSUE TITLE
Torches rendered strangely

### ISSUE THREAD

**Issue by Bobcat00** [overviewer/Minecraft-Overviewer#1852]
Here is a 2x magnification of a redstaone torch and a regular torch, each placed vertically on a sand block.  As you can see, there are strange artifacts alongside the torches.

![overviewer3](https://user-images.githubusercontent.com/3617206/94014856-1944d400-fd7a-11ea-9f06-b3eee8466745.png)

I don't know if this is due to Overviewer or the resource pack.

Spigot 1.16.3
Minecraft Overviewer version 0.16.5 (01ed588)
Resource pack PureBDCraft MC1.16 64x

On a related note, is it worthwhile using a 64x texture pack, or do you just scale everything down anyway?

**Comment by Bobcat00** [comment]
Hmmm...  Looks correct rendering with the default Minecraft 1.16.3 jar file.

![overviewer4](https://user-images.githubusercontent.com/3617206/94145390-7c00a300-fe40-11ea-8dba-822e08431cf6.png)

**Comment by Auron956** [comment]
Looks like it's probably due to that particular texture pack defining its own block model, which isn't supported with the way block textures are currently generated. I expect you'll be waiting on the implementation of texture generation based on block models before these torches are rendered properly, which has previously been discussed in #1772 & #1690 but unfortunately hasn't seen much movement for a while.

**Comment by Bobcat00** [comment]
Thanks for the explanation and links to other issues. I thought Overviewer would use the resource pack for rendering everything.  I'll just stick with the default textures built into the MC jar file, as ugly as they are.

Since other issues address this, I'm going to close this issue.
