### ISSUE TITLE
Cannot find level.dat file

### ISSUE THREAD

**Issue by Japple42** [overviewer/Minecraft-Overviewer#1865]
Running overviewer on windows 10 though the command prompt, trying to render my spigot minecraft server. The program renders the vanilla backups of the server just fine, but when I try to render the spigot version it just gives me "no level.dat file, are you sure that this is right?". No option to confirm, not sure why this happens (there is a level.dat file RIGHT THERE). If anyone could tell me how to fix this issue, that would be awesome. If you want me to provide any other information, let me know.

**Comment by LeadMagnet** [comment]
Only time I have seen this file is when the render takes place at the same time as a lot of server activity.

Not sure why, but it seems to be a file locking issue with level.dat. Which is why the offline renders of your backups run fine.

In my case, I always take a backup, then render from that, so never have this issue.

What happens why you try rendering with the MC server shutdown?

**Comment by Japple42** [comment]
That's...... what I'm doing. I'm not trying to render the server while it's online. Ever.

**Comment by Japple42** [comment]
Never mind, I'm dumb lol. Tried rendering by selecting the server folder, not the world folder in it.
