### ISSUE TITLE
Setting to limit CPU usage

### ISSUE THREAD

**Issue by developomp** [overviewer/Minecraft-Overviewer#1905]
While the minecraft overviewer is rendering the map images, the CPU usage spikes up to 100% and it makes the computer completely unusable for other heavy tasks. Since A relative small map can take a while to finish and some people including myself host a minecraft server on their own machine I think a option/config to limit CPU usage is important enough to be added to the software. I'm on Linux OS and tried using [cpulimit](https://github.com/opsengine/cpulimit) to limit the usage manually but the program launches multiple processes which makes it annoying to set a limit for all of the processes.

Any response (not necessarily with a good news) would be greatly appreciated.
Many thanks in advance <3.

**Comment by CounterPillow** [comment]
Set the niceness of overviewer to make scheduling prefer other processes. Limiting CPU usage per se makes no sense since you don't want your CPU to be idle, you just want other tasks to take precedence during task switching decisions the scheduler makes, which is precisely what `nice` does and your scheduler will respect.

**Comment by CounterPillow** [comment]
Alternatively you can use `chrt(1)` (see: `man 1 chrt`) to set the `-i` "idle" policy, which makes the process so incredibly low priority that it will only be run if the CPU is otherwise idle.
