### ISSUE TITLE
Blue torches are not being rendered

### ISSUE THREAD

**Issue by daveseff** [overviewer/Minecraft-Overviewer#1909]
It seems that blue torches are not being rendered. That is all. Thanks.

**Comment by IncredibleHolg** [comment]
Hi,
check #1807 
Lots of issues are coded but not merged into the main branch at the moment.

**Comment by drnixon** [comment]
If #1901 is merged it should take care of this issue, as a lot of prior work including #1807 were merged into that pull request

**Comment by daveseff** [comment]
![Screenshot at 2021-04-13 12-33-05](https://user-images.githubusercontent.com/1735615/114488394-a129f700-9c54-11eb-9449-85f22f3a2dbd.png)
As of a few hours ago it looks like it still isn't rendering. I've attached a screenshot. All of blank areas in this aussie flag should have blue torches. It renders the emitted light, but not the torch itself.

**Comment by drnixon** [comment]
Pull request hasn’t been merged yet. If you want to see the blue torches now, you’ll have to build from Doregon’s branch as stated in #1901

**Comment by drnixon** [comment]
For comparison: This image from my map was generated using Doregon's branch. You can see that blackstone and soul torches are rendering correctly. If using the branch, you'll have to do a force render to regenerate, otherwise the block will only be redrawn if it has changed since last render.
<img width="603" alt="Screen Shot 2021-04-13 at 4 18 28 PM" src="https://user-images.githubusercontent.com/50930574/114622837-1c4ed580-9c74-11eb-92c4-cee723dc8ebf.png">

**Comment by CounterPillow** [comment]
Renders now in the latest version
