### ISSUE TITLE
"MyMap" folder takes a very long time to move or delete. Paired with very high hard drive usage when opened.

### ISSUE THREAD

**Issue by HonestSoul3** [overviewer/Minecraft-Overviewer#1918]
I followed the windows newbie guide and saved the render to my desktop in a folder named "MyMap". Afterwards I tried moving the folder but was met with a "0%" loading bar that lasted over 10 minutes. 
I also tried uploading this folder to a few different online storage sites but this long load time prevented them all from being able to upload it. Even crashed the webpage a few times. 

Along with all this, every time I accessed the folder I was met with crippling HDD usage. Even after I closed the folder it stayed at 100% for several minutes before I restarted Windows Explorer in the task manager. After It restarted everything was back to normal. 

Upon opening the properties on the "MyMap" Folder I was met with something interesting. The size was going up rapidly despite nothing in the folder being in use (as far as I know). I watched it go from less than 1GB all the way up to 27GB where it stopped. 

I have since deleted this folder from my system due to the issues it was causing, and everything seems to be okay now. 

NOTE: The map rendered just fine and I was very happy with the results.

**Comment by CounterPillow** [comment]
The sad state of Windows NTFS small file performance is not really something we can do anything about. In short:

1. Overviewer writes its output in tiles, as this is the only proper way to deal with that much of pixel data, as we only want to decode a small amount of rendered map data when viewing the map as opposed to all of it (which nobody would have the RAM for, and would also exceed most image formats maximum image dimensions)
2. This results in a lot of somewhat small files spread across the quadtree.
3. Microsoft has not improved their file system layer since the late 90s, so they have massive overhead with file access, which means traversing a directory tree, moving files, deleting files, opening many small miles, etc. is all very slow. This is something they can't really fix with their current file system API, as it is overengineered and has a lot of slow paths they can't get rid of for compatibility's sake.

This is a well known issue for any Windows application, and it's why games use their own virtual filesystems within large "pack" files. We can't do this because we want to serve the output directories to web browsers directly.

Neither macOS nor Linux have this issue.
