### ISSUE TITLE
Not showing

### ISSUE THREAD

**Issue by bokey0000** [overviewer/Minecraft-Overviewer#1924]
![image](https://user-images.githubusercontent.com/83918432/117579995-3e7b2c80-b128-11eb-809b-fd25181c50b8.png)
For some reason, I only see a black screen. No world, nothing. How do I fix this?

**Comment by robosphinx** [comment]
The location pictured is extremely far from the center of your world (mouse shows coordinates x: 4.9 billion, z: -1.7 billion), which I suspect isn't intentional.   The other thing I notice is your zoom is shown as -27, which is really far out.  Try changing `559205/64/-5592590/-27` in your pictured URL to `0/64/0/max` to see if you have anything rendered at the center of your world.

This would make your URL `C:/Users/HP/OneDrive/Desktop/WOW/index.html#/0/64/0/max/world/world-lighting`
