### ISSUE TITLE
alternative texxture-pack when rendering

### ISSUE THREAD

**Issue by malandrinoor** [overviewer/Minecraft-Overviewer#1931]
I have rea the dos about overviewer and didn't quite get the texture-pack part. Is it possible to render the map with the same texture package that I have in minecraft or I can just use the "standard" one as default?  If so how can I manage to do the command thing on terminal since I have tried several times and failed to do so 😂

**Comment by CounterPillow** [comment]
The texture-pack can only be set from within a config file, if I remember right. Here's what you'll need:

1. a plain text editor, like notepad.exe or notepad++
2. turn the setting to show known file extensions ON in Windows explorer
3. a few minutes of your time

We'll start with a new output directory, usually mixing and matching stuff rendered without the config file and with the config file doesn't go well.

Create a file named something logical like `my_config.py` next to `overviewer.exe`. Make sure it is named `.py` and not `.py.txt`! That's why we need the known file extensions shown.

Put something like this into it, using the plain text editor of your choice:

```python
worlds["My world"] = "C:/where/your/world/is/"

renders["daytime"] = {
    "world": "My world",
    "title": "Day Time Render of My World",
    "rendermode": smooth_lighting
}

texturepath = "C:/path/to/your/textures.zip"
outputdir = "C:/where/you/want/your/map/to/be"
```

Replace `C:/path/to/your/textures.zip` with the actual path, same for  C:/where/you/want/your/map/to/be` and `C:/where/your/world/is/` but **ALWAYS USE FORWARD SLASHES!** Backwards slashes break the config file. Forward slashes work fine for specifying directories on windows.

Feel free to replace `Day Time Render of My World` with whatever you wish, it just needs to be in `"quotes like this"` and after the `"title":` on the same line.

Then you can render it using:

```
overviewer.exe -c my_config.py
```

where `my_config.py` is whatever filename you gave your config file.

Overviewer should now render your world to your output directory using the smooth_lighting rendermode and the texture pack you chose.
