### ISSUE TITLE
Does it work for 1.19?

### ISSUE THREAD

**Issue by FrancescoTurrini** [overviewer/Minecraft-Overviewer#2043]
Hi, I'm trying to make a map with overviewer of a seed 46942827301. But it continue to crash when it reaches 7%/8%. It crashes the entire computer

**Comment by Hraefin** [comment]
I just rendered a map for 1.19 after updating to the latest version and updating the textures.
It looks fine with the exception that it doesn't seem to want to render mangrove wood (in the trees) at all.
Not very tested since this was a new world with only view-distance worth of chunks loaded.

But TL;DR  yes.

**Comment by CounterPillow** [comment]
> It crashes the entire computer

your system being unstable under high CPU load is not an overviewer bug but a problem with your computer. 1.19 worlds will render, the new blocks just won't show up yet.
